export const ActionTypes = {
    SET_HEROS : 'SET_HEROS',
    ADD_TEAM_MEMBER : 'ADD_TEAM_MEMBER',
    SET_SELECTING_HERO: 'SET_SELECTING_HERO',
    CLEAN_TEAM: 'CLEAN_TEAM',

    SET_USER: 'SET_USER',
    SET_ISLOGIN: 'SET_ISLOGIN',

    SET_FILTER_BY_ALIGMENT: 'SET_FILTER_BY_ALIGMENT',
    SET_FILTER_BY_APHABET: 'SET_FILTER_BY_APHABET'
}